"""Add role to User

Revision ID: 15c8f3c3f3c7
Revises: 16f2112e7b36
Create Date: 2025-05-28 18:25:08.409814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c8f3c3f3c7'
down_revision = '16f2112e7b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fear', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_toxic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('toxicity_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fear', schema=None) as batch_op:
        batch_op.drop_column('toxicity_score')
        batch_op.drop_column('is_toxic')

    # ### end Alembic commands ###
