"""add toxicity fields to Comment

Revision ID: 66dbbfa6bad5
Revises: 91f30d96bf70
Create Date: 2025-05-22 15:06:28.611616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66dbbfa6bad5'
down_revision = '91f30d96bf70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_toxic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('toxicity_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('toxicity_score')
        batch_op.drop_column('is_toxic')

    # ### end Alembic commands ###
