"""Add emotion and score to Fear model

Revision ID: 71d7a438a900
Revises: 7426f5a9be3a
Create Date: 2025-05-20 20:37:04.331530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d7a438a900'
down_revision = '7426f5a9be3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fear', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fear', schema=None) as batch_op:
        batch_op.drop_column('score')
        batch_op.drop_column('emotion')

    # ### end Alembic commands ###
