"""remove emotion and score columns from Fear table

Revision ID: 91f30d96bf70
Revises: 71d7a438a900
Create Date: 2025-05-22 14:55:58.208581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f30d96bf70'
down_revision = '71d7a438a900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fear', schema=None) as batch_op:
        batch_op.drop_column('emotion')
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fear', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('emotion', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
